In [6]:
print ("solomom")

solomom


In [7]:

pip install numpy

In [23]:
import numpy as sm

In [26]:
re = sm.arange(10);
re.min()
re.max()
re.sum()
sm.sqrt(re)
sm.std(re)
re[9]
re[5]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
#slice
#[start:end:step]
re[:]#display all array
re[2:5:2]
re[:2:-2]

array([9, 7, 5, 3])

In [64]:
#two diamention array
arr1 = sm.array([[10,20],[30,40]])
arr1.shape
arr1.sum(axis =1)
arr2 =sm.array([20,30])
arr1.dot(arr2)


array([ 800, 1800])

In [11]:
re.dtype

dtype('int64')

In [12]:
pip install pandas

In [6]:
import pandas as pd
data = pd.read_csv("/content/Bigmarket (5).csv")
data.head() #first five record show(0-5)
data.tail() #Last five record show(5-0)
data.shape #Total nof rows and column count
data.info() # Table info like count of column, rangeIndex and datatype



<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Month   25 non-null     object
 1   Store   25 non-null     object
 2   Sales   25 non-null     int64 
dtypes: int64(1), object(2)
memory usage: 728.0+ bytes


0     31037
1     20722
2     24557
3     34649
4     29795
5     29133
6     22695
7     28312
8     31454
9     46267
10    32961
11    26451
12    47814
13    36069
14    31874
15    27253
16    40241
17    47488
18    25432
19    33880
20    29487
21    40001
22    46482
23    46313
24    47594
Name: Sales, dtype: int64

In [94]:
data['Sales']#Display sales column
data[['Sales','Store']]#display both column
data[data.Store == 'A']#display only Store 'A' data

Month Store  Sales
0     Jan     A  31037
5     Feb     A  29133
10  March     A  32961
15    Apr     A  27253
20    May     A  29487

In [89]:
data.sort_values('Sales',ascending=False)

Month Store  Sales
12  March     C  47814
24    May     E  47594
17    Apr     C  47488
22    May     C  46482
23    May     D  46313
9     Feb     E  46267
16    Apr     B  40241
21    May     B  40001
13  March     D  36069
3     Jan     D  34649
19    Apr     E  33880
10  March     A  32961
14  March     E  31874
8     Feb     D  31454
0     Jan     A  31037
4     Jan     E  29795
20    May     A  29487
5     Feb     A  29133
7     Feb     C  28312
15    Apr     A  27253
11  March     B  26451
18    Apr     D  25432
2     Jan     C  24557
6     Feb     B  22695
1     Jan     B  20722

In [91]:
officeITC = {'name':['sol','mon','mayer','renil','deni'],
             'address':['nager','coil','kanya','kumari','india']}#new Dict
mydata = pd.DataFrame(officeITC)#Add to Panda dataframe
mydata #display from dataframe like table

name address
0    sol   nager
1    mon    coil
2  mayer   kanya
3  renil  kumari
4   deni   india